# 论文/基准测试用已知 Work 注册表（与 scripts/main_case.py 对齐）
KNOWN_WORK_REGISTRY = {
    # Corpus
    "Wikipedia": "wiki_text = Work('Wikipedia', 'data', 'raw', 'CC-BY-SA-4.0') # Corpus",
    "StackExchange": "stack_exchange_text = Work('StackExchange', 'data', 'raw', 'CC-BY-SA-4.0') # Corpus",
    "FreeLaw": "free_law_text = Work('FreeLaw', 'data', 'raw', 'CC-BY-ND-4.0') # Corpus",
    "arXiv": "arxiv_text = Work('arXiv', 'data', 'raw', 'CC-BY-NC-SA-4.0') # Corpus",
    "PubMed": "pubmed_text = Work('PubMed', 'data', 'raw', 'CC-BY-NC-ND-4.0') # Corpus",
    "Deep-sequoia": "deep_sequoia_text = Work('Deep-sequoia', 'data', 'raw', 'LGPL-LR') # Corpus",
    # Image
    "Midjourney_gen": "midjourney_img = Work('Midjourney_gen', 'data', 'raw', 'CC-BY-NC-4.0') # Image",
    "Flickr": "flickr_img = Work('Flickr', 'data', 'raw', 'CC-BY-NC-SA-4.0') # Image",
    "StockSnap": "stocksnap_img = Work('StockSnap', 'data', 'raw', 'CC0-1.0') # Image",
    "Wikimedia": "wikimedia_img = Work('Wikimedia', 'data', 'raw', 'CC-BY-SA-4.0') # Image",
    "OpenClipart": "open_clipart_img = Work('OpenClipart', 'data', 'raw', 'CC0-1.0') # Image",
    # Music
    "ccMixter": "ccmixter_music = Work('ccMixter', 'data', 'raw', 'CC-BY-NC-4.0') # Music",
    "Jamendo": "jamendo_music = Work('Jamendo', 'data', 'raw', 'CC-BY-NC-ND-4.0') # Music",
    # 3D & Video
    "Thingverse": "thingverse_3d = Work('Thingverse', 'data', 'raw', 'CC-BY-NC-SA-4.0') # 3D Model",
    "Vimeo": "vimeo_video = Work('Vimeo', 'data', 'raw', 'CC-BY-NC-ND-4.0') # Video",
    # Models
    "Baize": "baize_model = Work('Baize', 'model', 'raw', 'GPL-3.0') # Chatbot",
    "StableDiffusionn": "stable_diffusion_mode = Work('StableDiffusion', 'model', 'raw', 'CreativeML-OpenRAIL-M') # Text2Image",
    "Whisper": "whisper_model = Work('Whisper', 'model', 'raw', 'MIT') # Voice2Text",
    "MaskFormer": "maskformer_model = Work('MaskFormer', 'model', 'raw', 'CC-BY-NC-4.0') # Image Segmentation",
    "DETR": "detr_model = Work('DETR', 'model', 'raw', 'Apache-2.0') # Image Segmentation",
    "X-Clip": "xclip_model = Work('X-Clip', 'model', 'raw', 'MIT') # Video2Text",
    "I2VGen-XL": "i2vgen_model = Work('I2VGen-XL', 'model', 'raw', 'CC-BY-NC-ND-4.0') # Image2Video",
    "BigTranslate": "bigtranslate_model = Work('BigTranslate', 'model', 'raw', 'GPL-3.0') # Text Translation",
    "BERT": "bert_model = Work('BERT', 'model', 'raw', 'Apache-2.0') # Text",
    "BLOOM": "bloom_model = Work('BLOOM', 'model', 'raw', 'BigScience-BLOOM-RAIL-1.0') # Text Generation",
    "Llama2": "llama2_model = Work('Llama2', 'model', 'raw', 'Llama2') # Text Generation",
    "fake_work3": "fake_work3 = Work('tencent/HunyuanVideo-1.5', 'model', 'raw', 'Unknow')",
}

registered_work = KNOWN_WORK_REGISTRY

WORK_ALIASES = {
    "wiki": "Wikipedia",
    "wikipedia": "Wikipedia",
    "stack exchange": "StackExchange",
    "stackexchange": "StackExchange",
    "free law": "FreeLaw",
    "freelaw": "FreeLaw",
    "arxiv": "arXiv",
    "pubmed": "PubMed",
    "deep sequoia": "Deep-sequoia",
    "deep-sequoia": "Deep-sequoia",
    "midjourney": "Midjourney_gen",
    "midjourney_gen": "Midjourney_gen",
    "flickr": "Flickr",
    "stocksnap": "StockSnap",
    "wikimedia": "Wikimedia",
    "ccmixter": "ccMixter",
    "jamendo": "Jamendo",
    "thingverse": "Thingverse",
    "vimeo": "Vimeo",
    "baize": "Baize",
    "stable diffusion": "StableDiffusionn",
    "stablediffusion": "StableDiffusionn",
    "stable diffusionn": "StableDiffusionn",
    "whisper": "Whisper",
    "maskformer": "MaskFormer",
    "detr": "DETR",
    "x-clip": "X-Clip",
    "xclip": "X-Clip",
    "i2vgen": "I2VGen-XL",
    "i2vgen-xl": "I2VGen-XL",
    "i2vgen xl": "I2VGen-XL",
    "bigtranslate": "BigTranslate",
    "big translate": "BigTranslate",
    "bert": "BERT",
    "bloom": "BLOOM",
    "llama2": "Llama2",
    "llama 2": "Llama2",
}
